# Generated by Django 5.0.6 on 2024-09-12 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nam', models.CharField(max_length=250)),
                ('im', models.ImageField(upload_to='pics')),
                ('des', models.TextField()),
            ],
        ),
    ]
